SELECT STUDENTS.NAME, STUDENTS.SURNAME, STUDENTS.AGE, STUDENTS.DEPARTAMENT,
AVG(STUDENTS.AGE) OVER (PARTITION BY STUDENTS.DEPARTAMENT) AS avg_age,
MAX(STUDENTS.AGE) OVER (PARTITION BY STUDENTS.DEPARTAMENT) AS max_age,
MIN(STUDENTS.AGE) OVER (PARTITION BY STUDENTS.DEPARTAMENT) AS min_age
FROM STUDENTS