WITH CTE (STAIR) AS (
	SELECT STAIR, ROW_NUMBER () OVER (PARTITION BY STAIR) AS row_num
	FROM (SELECT STAIR FROM STUDENT_STAIR_REGISTER) AS student_stairs
					)

SELECT STAIR
FROM CTE
WHERE row_num = 1;