SELECT STUDENTS.NAME, STUDENTS.SURNAME
FROM STUDENTS
WHERE STUDENTS.ID IN (SELECT STUDENT_STAIR_REGISTER.STUDENT
					 FROM STUDENT_STAIR_REGISTER
					 WHERE STUDENT_STAIR_REGISTER.STAIR BETWEEN 1000 AND 1500);