SELECT TEACHER_STAIR_REGISTER.TEACHER, TEACHER_STAIR_REGISTER.STAIR
FROM TEACHER_STAIR_REGISTER
WHERE EXISTS(
	SELECT TEACHER_STAIR_REGISTER.ID 
	FROM TEACHER_STAIR_REGISTER, TEACHERS
	WHERE (TEACHER_STAIR_REGISTER.TEACHER = TEACHERS.ID AND TEACHERS.AGE BETWEEN 30 AND 40))
	AND TEACHER_STAIR_REGISTER.STAIR BETWEEN 0 AND 1000;