SELECT STAIRS.ID, STAIRS.STAIRCASE_ID, STAIRS.STEP_NUM
FROM STAIRS
WHERE STAIRS.ID = ANY (
	SELECT STUDENT_STAIR_REGISTER.STAIR
	FROM STUDENT_STAIR_REGISTER
	WHERE STUDENT_STAIR_REGISTER.ENTRY_DATE = '25.10.2020'
					  );