SELECT STUDENTS.NAME, STUDENTS.SURNAME, STUDENTS.AGE,
(SELECT MAX(STAIR)
FROM STUDENT_STAIR_REGISTER
WHERE STUDENT_STAIR_REGISTER.STUDENT = STUDENTS.ID) AS AvgStair
FROM STUDENTS
WHERE STUDENTS.DEPARTAMENT = 'ИУ7';